---
title: simudin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: harudin91@gmail.com
description: 'Hi! I''m Hasim Sofaruddin. A Web Developer from Sumedang, Indonesia.
  I write about programming and other technical things here.

'
baseurl: 
url: http://simudin.github.io
twitter_username: simudin
github_username: simudin
markdown: kramdown
