# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: simudin
email: harudin91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Hasim Sofaruddin. A Web Developer from Sumedang,
  Indonesia. I write about programming and other technical things here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://simudin.github.io" # the base hostname & protocol for your site
twitter_username: simudin
github_username:  simudin

# Build settings
markdown: kramdown
